server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultAone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务列表间隔时间
zuul:
  prefix: /api
  routes:
    item-service: /item/**  #路由到商品微服务


